### ISSUE TITLE
Requesting revision of timezone-olson 0.1.9 with looser time bound

### ISSUE THREAD

**Issue by ysangkok** [ygale/timezone-olson#11]
I see the repo has advanced to the 0.2 series. But there are still libraries such as timezone-olson-th that depend on the 0.1.* series. I noticed that the 0.1.9 release works just fine with `time<1.14` instead of its current `time<1.10` bound. I am having a problem compiling with time 1.9 on GHC 9.2, so I would appreciate if this bound could be loosened. Thank you.

**Comment by ygale** [comment]
@ysangkok Thanks! Actually, it does not work 100% fine, and this appears to have been a problem for a while.

Since time 1.9.1 the API for formatting and parsing time types changed. We updated this library based on a submitted PR, but there are some problems with that.

I see that we get a GHC warning that one of the required methods of the `ParseTime` class - namely `parseTimeSpecifier` - is not defined. That could lead to runtime crashes for people using that instance.

~Furthermore, I now see that we were not careful about maintaining support of versions of time previous to 1.9.1 for the formatting and parsing classes, despite our claim that we support them.~ I checked more carefully  - support for older time versions is OK.

I will try to fix these things soon. As a side effect, the max version of the time library dependency will be bumped as you request.

If you would like to submit a PR for those things, I would be grateful, and it might happen a little faster. Please let me know if you are interested.

**Comment by ygale** [comment]
@AshleyYakeley Hmm don't I need to use `timeParseTimeSpecifier` and `timeSubstituteTimeSpecifier` to complete my instances? But those are hidden. Am I supposed to copy/paste their definitions into my code? That doesn't seem very robust. What am I missing?

**Comment by ygale** [comment]
@ysangkok Fixed in version 0.2.1
